language: rust

services:
  - docker

env:
  global:
    - PROJECT_NAME=roseline

matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
      addons:
        apt:
          packages:
            - openssl
    - os: linux
      rust: stable
      env: TARGET=armv7-unknown-linux-gnueabihf
      addons:
        apt:
          packages: *armhf

sudo: true

install:
  - sudo apt update && sudo apt upgrade openssl
  - openssl version
  - sh ci/install.sh

script:
  - echo -n $DISCORD_TOKEN > bot/discord.token
  - sh ci/script.sh

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}*
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  overwrite: true
  # deploy when a new tag is pushed
  on:
    # channel to use to produce the release artifacts
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
