[package]
name = "int-vndb"
version = "0.1.0"
authors = ["Douman <douman@gmx.se>"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
slog = "2"
slog-scope = "4"

tokio-core = "0"
futures = "0"

vndb = "0"
