[package]
name = "utils"
version = "0.1.0"
authors = ["Douman <douman@gmx.se>"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
cute-log = "1"
lazy-panic = "0.3"

[target."cfg(all(unix, not(target_os = \"macos\")))".dependencies]
openssl-probe = "0"
